### ISSUE TITLE
speech analytics API Integration

### ISSUE THREAD

**Issue by emilianop11** [voxbone-workshop/Speech-analytics-Cloud-Functions#1]

**Comment by chadwallacehart** [comment]
@emilianop11 - what's the purpose of this Epic? Is it supposed to be on this repo?

**Comment by emilianop11** [comment]
@chadwallacehart This was used in the past, when we didnt even had voxbone.ai. We were using stand-alone lambda functions in AWS. This epic was to determine which other transcription api's include in those functions.
I think we can close it now, since it's a duplicate of whats happening on voxbone.ai board.
